### ISSUE TITLE
Doesn't work on Some IE versions

### ISSUE THREAD

**Issue by yubin-park** [yubin-park/emory-covid19#1]
People mentioned that the site doesn't work on some versions of IE

**Comment by yubin-park** [comment]
@StarLiu1 Could you check our polyfill patch solved the issue? Thanks!

**Comment by StarLiu1** [comment]
@yubin-park Yes. I used the following user agent in Safari for IE9 and IE11: 
"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; KTXN)"
"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

They both work!

**Comment by yubin-park** [comment]
Great! Closing the issue for now.
